{% set version = "2.2.1" %}

package:
  name: pathlib2
  version: {{ version }}

source:
  fn: pathlib2-{{ version }}.tar.gz
  url: https://github.com/mcmtroffaes/pathlib2/archive/{{ version }}.tar.gz
  sha256: 3ea36fb93e514e85360083f02a2d025ebe17b685c704ae035d1626d1d2b381fc

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - six
    - scandir  # [py27]

test:
  imports:
    - pathlib2

about:
  home: https://github.com/mcmtroffaes/pathlib2
  license: MIT
  license_file: LICENSE.rst
  summary: "Fork of pathlib aiming to support the full stdlib Python API."

extra:
  recipe-maintainers:
    - pelson
    - takluyver
