{% set name = "pathlib2" %}
{% set version = "2.3.7.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9fe0edad898b83c0c3e199c842b27ed216645d2e177757b2dd67384d4113c641

build:
  number: 0
  skip: True  # [py<35]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - six
    - scandir  # [py<35]
    - typing  # [py<35]

# Windows path assertion
# WindowsPath('C:/cygwin64/home/builder-admin') != 
# WindowsPath('C:/Users/builder-admin')
{% set SKIP_TEST_WIN64 = [
    "test_expanduser_common",
    "test_home"
] %}

test:
  files:
    - sitecustomize.py
  source_files:
    - tests
  imports:
    - pathlib2
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - cp "${RECIPE_DIR}/sitecustomize.py" . && export PYTHONPATH="${SRC_DIR}:${PYTHONPATH}"  # [unix]
    - cp "%RECIPE_DIR%/sitecustomize.py" . && set PYTHONPATH=%SRC_DIR%;%PYTHONPATH%  # [win]
    - pytest tests -v  # [unix]
    - pytest tests -v -k "not ({{ SKIP_TEST_WIN64 | join(' or ') }})"  # [win]

about:
  home: https://github.com/jazzband/pathlib2
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: Fork of pathlib aiming to support the full stdlib Python API
  description: |
    The goal of pathlib2 is to provide a backport of standard pathlib module which
    tracks the standard library module, so all the newest features of the standard
    pathlib can be used also on older Python versions.
  doc_url: https://github.com/jazzband/pathlib2/tree/develop/docs
  dev_url: https://github.com/jazzband/pathlib2

extra:
  recipe-maintainers:
    - pelson
    - takluyver
