travis:
  secure:
    BINSTAR_TOKEN: uy0Ct1HVh9055RJYlJjDI08Gd52e3SilVuSMzerQqgkJaz1c33nGwef1O1ag290VTEwncXXa7GyPCYiBlOTjbigKACLCajivUPguXn2NVHHYFpDqnAGftQSkeyl7ManvVyQ/PJRpVfYPBP58PtdORauA3UmZDk8uhZKEjIpfwyHCK1a2ojJvje1EuKXyDAbtOGNmLlP+aAFq9QOfCd5mc9T/gLmIbdMI9G6bj2x/vPM9Y+RzjXf6QzRXoYbKUMiJnCBho4FITyhgd+a0Oyr52VQz4I6VPX+XLRIHgwA3OVgdtbbBQRD7eM90vhsqKEblo8p6hTuDxj9pvZNT0kVHIcPs68YmoUZYWh9P2MXodvDJ/USBm7i2Y1a/LMx9o73CeQzAeZ3OIPv5nk7Snlx4Fv61z0rbkJTrIVFacc5EGbgkNMky3BSEXRfOIDQATBKG93HhIW3j3YRP8si51ukKTH9FWr2gRuBSkTe+fSoOE07bm4mFAa8wx6QrtmCjRVhOA3Mi8a83CNZsnMStRj+sSc50ceHHgRn184udPJ+95RhlJdoKbx3hbbKVZ6q6gUMwZbi/As0L9lvTR884UdhmPosE7DzFC0+sVcIV4gVzGwJfon4c/cShT+FPpuhdFVsjmvTjWrmPc+R2s+i8vtyZeBnIyaoOIPfjxfzvoc1irfo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
